sudo: required

language: generic

env:
  - ARCH=amd64   
  - ARCH=i386    QEMU_BIN=i386
  - ARCH=armhf   QEMU_BIN=arm
  - ARCH=s390x   QEMU_BIN=s390x
  - ARCH=powerpc QEMU_BIN=ppc64
  - ARCH=mips    QEMU_BIN=mips
  - ARCH=mipsel  QEMU_BIN=mipsel
  - ARCH=armhf   QEMU_BIN=arm
  - ARCH=sparc   QEMU_BIN=sparc


script:
    - "./travis-ci-run.sh"
